MeasureTransport/MParT

CMakeLists.txt
When configuring the MParT build with cmake, adding the `-DMPART_BUILD_TESTS=OFF` will now prevent the tests from being installed.  This will also cause CMake to skip looking for, or clone, the Catch2 test library.
=> Added ability to turn tests on and off 

MParT/HermiteFunction.h, tests/Test_HermiteFunctions.cpp
In practice, we seem to use Hermite functions with an extra constant and linear term.   This pull requests add those terms to the 1d Hermite function scalar basis class.    An order of `n=0` now gives a constant value.   `n=1` will result in `x` and orders greater than 2 will result in the Hermite function of order `n-2`.
=> Hermite functions

bindings/python/package/__init__.py, bindings/python/src/CommonPybindUtilities.cpp
According to the [Kokkos docs](https://github.com/kokkos/kokkos/wiki/Initialization), the Kokkos configuration can be set at runtime by constructing an instance of the`Kokkos::InitArguments` class.  Previously we were just passing in arguments like they were set on the command line, but the Kokkos documentation seems to imply that if negative values are passed to `Kokkos::InitArguments`, then the default behavior is to use `hwloc` to find the default number of threads.   
Also added ability to check the amount of concurrency that Kokkos can exploit (e.g., the number of threads) using `mpart.Concurrency()` in python.
=> Changed python bindings to use structure-based Kokkos init.

.github/workflows/build-external-lib-tests.yml, MParT/Initialization.h, MParT/MultivariateExpansion.h, src/Initialization.cpp, tests/RunTests.cpp, tests/Test_MultivariateExpansion.cpp
Closes #130 
First argument to `MParT::Initialize` is now accepted by reference, which allows Kokkos to remove arguments from the command line inputs and allows Catch2 to function properly.
=> Update MParT::Initialize so that Kokkos can update argc.

MParT/ConditionalMapBase.h, MParT/MonotoneComponent.h, MParT/MultivariateExpansion.h, MParT/ParameterizedFunctionBase.h, MParT/TriangularMap.h, MParT/Utilities/ArrayConversions.h, bindings/matlab/mat/ConditionalMap.m, bindings/matlab/src/ConditionalMap_mex.cpp, bindings/matlab/src/MexArrayConversions.cpp, src/ConditionalMapBase.cpp, src/ParameterizedFunctionBase.cpp, src/TriangularMap.cpp, tests/Test_ArrayConversions.cpp, tests/Test_ConditionalMapBase.cpp
Closes #71 
Previously, we were using Kokkos views that were restricted to the default Kokkos memory layout (row-major on host code or column-major in device code).   When constructing arrays, I still use these defaults, but I updated the function definitions in `ConditionalMapBase` and `ParameterizedFunctionBase` to accepted general strided layouts.   This enables either row major OR column major formats to be used.  Strided layouts can also be used to grab "slices" or matrices without making copies.
One immediate benefit of this update is that we can now natively support the memory layouts of any other language, such as Matlab.   So we no longer need to copy memory when interfacing between matlab and MParT.
@rubiop I updated the Matlab bindings, but could you rerun your speed tests to …
=> Converted entire map stack to use Strided layouts.

src/MapFactory.cpp, tests/Test_MapFactory.cpp
Closes #97 
- Added additional branches to MapFactory::CreateComponent if statement to process `ClenshawCurtis` and `AdaptiveClenshawCurtis` quadrature rules.
- Added test to make sure we can build/evaluation components with these rules.
This crazy nested if statement is a clunky way of handling these options, but I'm not sure if there is a better way with the templating we're doing.
=> Added handling of other quadrature options.

CMakeLists.txt
Solves my troubles with multiple versions of Python.
=> explicitly search (and find) for python during cmake

CMakeLists.txt
Reverts MeasureTransport/MParT#166
See discussion in #167 .
=> Revert "explicitly search (and find) for python during cmake"

bindings/julia/include/CommonJuliaUtilities.h, bindings/julia/package/MParT.jl, bindings/julia/src/CommonJuliaUtilities.cpp, docs/source/getting_started.rst, docs/source/installation.rst
@rubiop pointed out some issues with the Julia bindings in the Julia docs and lack of support for kokkos threads. Now you should be able to do, e.g., 
```
$ export KOKKOS_NUM_THREADS=8
$ julia
...
julia> using MParT
```
and it will automatically start up with 8 threads (it should say so).
=> Fix issues with Julia

CMakeLists.txt, cmake/FindJulia.cmake
I know I keep doing this, but it needs to be changed again because the Julia bindings still don't work the way they should when pulling MParT.jl. I know it's not the most convenient way to compile them locally (and I'm open to adding some way for auto-detecting JlCxx), but I think a large problem is using the runtime-detected Julia.
=> Rearrange how Julia bindings are compiled

bindings/julia/CMakeLists.txt, cmake/SetInstallPaths.cmake
Similar to #201 , add the ability to install the julia binding target anywhere. Slightly different-- this does not automatically put the target under an `mpart` directory! I believe the issue being faced for MacOS in building could be attributed to just not having all the libraries in `lib`, and so I would like to make that an option.
=> Add option for Julia install path

bindings/matlab/mat/ConditionalMap.m, bindings/matlab/mat/TriangularMap.m, bindings/matlab/src/ConditionalMap_mex.cpp, bindings/matlab/src/FixedMultiIndexSet_mex.cpp, bindings/matlab/tests/Test_TriangularMap.m
Before this update the map component could be created from a `MultiIndexSet` (which is automatically fixed when calling the map component constructor in C++).
Now you can directly use a `FixedMultiIndexSet`. 
Maybe we should remove the ability of doing it directly from a `MultiIndexSet`.
=> Create component from a FixedMultiIndexSet

docs/index.rst, docs/source/getting_started.rst
- Added a paragraph to the home page of the documentation giving an overview of measure transport and what MParT looks to achieve.
- Made some small edits to the getting started/python section.
=> 207 docs intro and using python section

bindings/julia/src/MultiIndex.cpp
I realized that I messed up one-based vs. zero-based indexing in the bindings :/
=> Fix indexing for MultiIndexSets

MParT/Utilities/ArrayConversions.h, bindings/julia/src/ConditionalMapBase.cpp, tests/Test_ArrayConversions.cpp
To add GPU support for Julia (and, presumably, MATLAB), we need the `ToKokkos` functions working with DeviceSpace.
Additionally, this fixes a few small bugs with tests in the `TestArrayConversions`.
=> Add Kokkos array conversions

MParT/ComposedMap.h, src/ComposedMap.cpp, tests/Test_ComposedMap.cpp
Checkpointing based on the classic binomial approach of [[Griewank and Walther, 2000]](https://dl.acm.org/doi/10.1145/347837.347846) that seems to be used almost everywhere.   The number of checkpoints is passed to the constructor of the `ComposedMap` class and can be set based on the size of the problem and memory limitations.
There are two limiting cases:
1. If the number of checkpoints is set to 1, all previous layers are recomputed every step of the backward pass, just like we were doing before.
2. If the number of checkpoints is greater than or equal to the number of layers, then the inputs to every layer are stored.  This requires the least computation but the most memory.   
A limited amount of recomputation is  performed for any other number of checkpoints.
=> Added Checkpointing to ComposedMap class.

bindings/matlab/CMakeLists.txt, bindings/matlab/external/mexplus/mexplus/mxarray.h
Long story short, Mathworks changed how complex numbers were represented in 2018. While we don't really use complex numbers, it was actually easier to adapt Mexplus to support the new complex numbers than it was to remove them from the library. The old way is deprecated but not removed (though it will be at some point). CMAKE defaults to compiling MEX with the old standard, so we haven't had an issue, but if you want to test this for both, change `bindings/matlab/CMakeLists:18` between
` matlab_add_mex(NAME MParT_ SRC ${MEX_SOURCE} LINK_TO mpart Kokkos::kokkos Eigen3::Eigen R2017b)`
and
` matlab_add_mex(NAME MParT_ SRC ${MEX_SOURCE} LINK_TO mpart Kokkos::kokkos Eigen3::Eigen R2018a)`
if they both compile correctly and you can run some simple files, then everything should be A-okay.
=> Adapt MexPlus to enable interleaved complex

.docker/Dockerfile, .github/workflows/build-doc.yml, .github/workflows/build-external-lib-tests.yml, .github/workflows/build-tests.yml, CMakeLists.txt, MParT/Utilities/ArrayConversions.h, bindings/matlab/src/KokkosUtilities_mex.cpp, bindings/python/src/CommonPybindUtilities.cpp, docs/source/installation.rst
Currently, our build breaks with the new version of Kokkos. This makes that not happen.
=> Fix MParT to work with Kokkos 3.7

src/TriangularMap.cpp, tests/Test_TriangularMap.cpp
This adds checks to the CoeffGrad and LogDeterminantCoeffGrad functions in `TriangularMap` so that components with no coefficients are skipped. It also adds a test for `SingleEntryMap` that presented the issue.
=> 279 triangularmap handing map components without coefficients like identitymap

src/Distributions/GaussianSamplerDensity.cpp
When trying to build with pip, I ran into this error:
```
GaussianSamplerDensity.cpp:134:17: error: explicit instantiation of 'mpart::GaussianSamplerDensity' must occur in namespace 'mpart'
```
This pull request should fix that.
=> Fixing explicit instantiation must occur in namespace error.

MParT/AdaptiveTransportMap.h, MParT/MapObjective.h, MParT/TrainMap.h, bindings/julia/src/MapObjective.cpp, bindings/julia/src/TrainMap.cpp, bindings/matlab/include/MexWrapperTypes.h, bindings/matlab/mat/GaussianKLObjective.m, bindings/matlab/src/ConditionalMap_mex.cpp, bindings/matlab/src/MapObjective_mex.cpp, bindings/python/src/MapObjective.cpp, bindings/python/src/TrainMap.cpp, bindings/python/src/Wrapper.cpp, bindings/python/tests/test_TrainMap.py, src/AdaptiveTransportMap.cpp, src/MapObjective.cpp, src/TrainMap.cpp, tests/Test_AdaptiveTransportMap.cpp, tests/Test_TrainMap.cpp
I wasn't particularly satisfied with how `MapObjective` was used in the previous PRs, so I made a small change here that's kind of separate from the previous PRs. Now, I'm working to make `MapObjective` stays in shared pointers so we don't get weird necessary explicit templates like we did for `TrainMap<ObjectiveType>` (since `MapObjective` was an abstract type, you couldn't use it in the function declaration for `TrainMap`). I didn't realize how to fix it until after I submitted the PR, so it's better to just make a new one.
=> Changing integration of `MapObjective`

bindings/julia/src/JlArrayConversions.cpp, bindings/julia/src/MultiIndex.cpp
Also fixed a small bug-- the previous binding for `copy` actually was unnecessary and caused problems with Julia. I added an `addto!` binding for MultiIndexSet to check whether the given `copy` works.
=> Fix striding for eigen conversion in Julia binding

CITATION.cff, CMakeLists.txt, MParT/TrainMapAdaptive.h, MParT/Utilities/ArrayConversions.h, bindings/python/src/MultiIndex.cpp, pyproject.toml, setup.py
Segfaults were occurring when manually creating a `FixedMultiIndexSet` in python because of a shallow copy of a temporary vector in the python bindings for the `FixedMultiIndexSet` constructor.  This PR fixes the issue with deep copies.
Also fixes a bug in the `ConstVecToKokkos` function that showed up when exploring fixes to the python bindings.
=> Fixed bug in `FixedMultiindexSet` python bindings

tests/Test_ComposedMap.cpp, tests/Test_TrainMap.cpp, tests/Test_TrainMapAdaptive.cpp, tests/Test_TriangularMap.cpp
RunTests was getting too lengthy for reasonable TDD, so I removed some redundant tests for when `moveCoeffs=true` from `Test_TriangularMap`, cranked down the complexity of some of those tests, and then cranked down the complexity of the ComposedMap depth (I think if it can handle 5, it can handle 8, but the time complexity goes up exponentially, which is unnecessary for tests). I commented out (🤮 ) some tests in TrainMapAdaptive which were somewhat redundant, because that algorithm is really expensive and we need to optimize it a little bit, so about 50% of the runtime of the tests is now from that one ATM call.
=> Streamline some unit/regression tests

MParT/MonotoneComponent.h, MParT/MonotoneIntegrand.h, MParT/Sigmoid.h, MParT/Utilities/RootFinding.h, tests/CMakeLists.txt, tests/Test_MonotoneComponent.cpp, tests/Test_RootFinding.cpp, tests/Test_Sigmoid.cpp
- Creates linear sigmoid 1d basis (often called "RBFs", we actually care about using the integral of the RBF, which is a sigmoid function in most literature)
- Allows for centers and widths to allow for more expressible functions
- Moves the 1d root finding to external file, which will be needed for multiple different function representations (and also cleans up the file)
=> Add sigmoid, move root finding

MParT/MonotoneComponent.h, MParT/Utilities/Miscellaneous.h, MParT/Utilities/RootFinding.h, tests/Test_RootFinding.cpp
We were running into issues where an initial bracket could not be found during the map inversion because the map was essentially flat.  In this situation, the inverse would just hang.  This PR changes the way error handling is done inside the bracketed inverse to avoid this silent hang.  It also adds a basic check to determine of the function we're tracking to bracket is essentially flat.
=> Fix silent hang in map inversion.

.github/environment.yml, MParT/Utilities/ArrayConversions.h, bindings/python/package/__init__.py, bindings/python/package/torch.py, bindings/python/src/ConditionalMapBase.cpp, bindings/python/src/ParameterizedFunctionBase.cpp, bindings/python/tests/test_TorchWrapper.py, tests/Test_ArrayConversions.cpp
- Allows an MParT `ParameterizedFunctionBase` or `ConditionalMapBase` object to be used as a module in torch.  This allows torch autograd to propagate gradients through maps and allows neural networks and transport maps to be blended into more complex models.
- Importantly, we do not require pytorch during compilation.  The MParT <-> PyTorch interface will only be include with the python bindings if pytorch if available at the time of `import`
- Pytorch tensors are not copied when calling MParT.  We simply wrap unmanaged Kokkos::Views around the memory in the pytorch tensor.
- Currently only supports pytorch tensors that live on the CPU, but could be extended to work with GPU tensors as well.
- An example using this interface for heteroscedastic regression is in an[ accompanying PR into …
=> PyTorch Interface

bindings/matlab/src/ConditionalMap_mex.cpp, bindings/matlab/src/ParameterizedFunctionBase_mex.cpp
Fixes #360 , which was caused by an off-by-one error introduced in #353 .
=> Fix matlab options

bindings/julia/src/TriangularMap.cpp, tests/Distributions/Test_Distributions_Common.h
This was omitted in previous versions.
=> Add move coeffs positional argument for julia binding

MParT/MultiIndices/FixedMultiIndexSet.h, src/MultiIndices/FixedMultiIndexSet.cpp, tests/MultiIndices/Test_MultiIndexSet.cpp
Ensures FixedMultiIndexSets have the order required in #372 .   To make sure everything can run on host or device, this usess an implementation of selection sort inside a functor evaluated by `Kokkos::parallel_for`.    Any speed savings possible using `std::sort` or something more sophisticated is probably negligible for the dimensions we typically work with.
=> Added sort of nzDims in manual construction of FixedMultiIndexSet.

CMakeLists.txt, MParT/TrainMap.h, MParT/Utilities/LinearAlgebra.h, bindings/julia/src/CommonJuliaUtilities.cpp, src/Distributions/GaussianSamplerDensity.cpp, src/MapObjective.cpp, tests/Test_LinearAlgebra.cpp, tests/Test_TrainMapAdaptive.cpp
Changes to support Kokkos 4.  This version of kokkos no longer supports volatile arguments to lambda functions and I therefore replaced the `ReduceDim` class with direct uses of nested `parallel_for` and `parallel_reduce` calls.
=> Kokkos update

.docker/environment.yml, .github/environment.yml, .github/workflows/build-bindings.yml, .github/workflows/build-doc.yml, .github/workflows/build-external-lib-tests.yml, .github/workflows/build-push-docker.yml, .github/workflows/build-tests.yml, bindings/python/package/torch.py, bindings/python/package/torch_helpers.py, bindings/python/tests/test_TorchWrapper.py, pyproject.toml, tests/Distributions/Test_SampleGenerator.cpp
- Fixed a bug in the serialization of the pytorch wrapper using dill or pickle.  The bug manifested in the following warning:
```bash
PicklingWarning: Cannot pickle <class 'mpart.torch.MpartTorchAutograd'>: mpart.torch.MpartTorchAutograd has recursive self-references that trigger a RecursionError.
```
- Updated workflows and dependencies to support new `release` branch.
=> Pickle Bugfix
