- src/MultiIndices/MultiIndexSet.cpp
- tests/MultiIndices/Test_MultiIndexSet.cpp
Closes #156 
- Added test to capture the visualization issue @rubiop reported.
- Fixed visualization function to support "floating" multiindices.
> Fixed MultiIndexSet Visualization and added test to catch this.

- README.md
> add binder batch to README

- CMakeLists.txt
- docs/source/installation.rst
Fixes a problem that causes a bug in julia when working with the bindings. Also add docs for how to install the Julia bindings now.
> Remove julia headers

- docs/conf.py
- docs/source/development/index.rst
- docs/source/getting_started.rst
I didn't realize we were already using `sphinx-design`. I'll use the tabs accordingly
> Fix tab problem

- CMakeLists.txt
- cmake/FindJulia.cmake
@rubiop and @dannys4 , Could you verify that these changes to CMake still work for each of you?
> Attempted fix of FindJulia.cmake when Julia is not present.

- docs/source/development/index.rst
Not complete yet; step by step. :-D
> added some info about community and how to engage

- MParT/MultiIndices/MultiIndex.h
- MParT/MultiIndices/MultiIndexSet.h
- MParT/ParameterizedFunctionBase.h
- bindings/matlab/mat/FixedMultiIndexSet.m
- bindings/matlab/mat/MultiIndexSet.m
- bindings/matlab/src/MultiIndexSet_mex.cpp
- src/MultiIndices/MultiIndexSet.cpp
- tests/MultiIndices/Test_MultiIndexSet.cpp
Fixed indexing in the inputs and outputs of few MultiIndexSet matlab bindings
> Fix consistency of indexing in Matlab bindings

- .github/workflows/build-doc.yml
That one should be merged after https://github.com/MeasureTransport/MParT-examples/pull/24. 
Edit: And after the discussion https://github.com/MeasureTransport/MParT/discussions/199.
> Update docs to new docker

- bindings/julia/src/MultiIndex.cpp
Small Patch to make Gradient example work
> Add CreateTotalOrder for Julia

- docs/source/installation.rst
This only modifies documentation to reflect the current status of the package. Fixes #232
> Fix Julia source installation docs

- bindings/julia/CMakeLists.txt
- bindings/julia/include/CommonJuliaUtilities.h
- bindings/julia/src/AffineMap.cpp
- bindings/julia/src/CommonJuliaUtilities.cpp
- bindings/julia/src/ComposedMap.cpp
- bindings/julia/src/ConditionalMapBase.cpp
- bindings/julia/src/ParameterizedFunctionBase.cpp
- bindings/julia/src/TriangularMap.cpp
- bindings/julia/src/Wrapper.cpp
Commented out `EvaluateUntilK` due to odd `Layout` requirements.
> Adding bindings for Julia affine and composed map classes

- MParT/ComposedMap.h
- docs/source/api/composedmap.rst
- docs/source/api/index.rst
- src/ComposedMap.cpp
Added documentation for the `ComposedMap` class.
> 263 correct composedmap documentation

- bindings/matlab/mat/AffineMap.m
- bindings/matlab/mat/ComposedMap.m
- bindings/matlab/mat/ConditionalMap.m
- bindings/matlab/src/ConditionalMap_mex.cpp
- bindings/matlab/src/MultiIndexSet_mex.cpp
- bindings/matlab/tests/Test_AffineMap.m
- bindings/matlab/tests/Test_ComposedMap.m
At this point I only tested bindings on simple examples but creations of objects are working fine and I haven't touch the methods (ses `tests/Test_AffineMap.m `and` tests/Test_ComposedMap.m`).
Should also close #255
> 253 matlab bindings for composedmap class

- bindings/matlab/tests/Test_TriangularMap.m
- src/TriangularMap.cpp
- tests/Test_TriangularMap.cpp
1. Changed TriangularMap constructor to allow for map components of different dimensions.
2. Added a test for a TriangularMap made with 3 smaller TriangularMaps of different dimensions.
> 261 triangularmaps constructor bug

- bindings/matlab/src/KokkosUtilities_mex.cpp
Fixing an issue introduced in #273 with Matlab.
> Change matlab initialization

- MParT/AffineFunction.h
- bindings/python/src/AffineMap.cpp
- bindings/python/tests/test_AffineFunction.py
- bindings/python/tests/test_AffineMap.py
- bindings/python/tests/test_ComposedMap.py
- bindings/python/tests/test_ConditionalMapBase.py
- bindings/python/tests/test_TriangularMap.py
- src/AffineFunction.cpp
- src/AffineMap.cpp
- Deep copying of `A` and/or `b` in constructors for AffineMap and AffineFunction
- Added python unit tests of AffineMap and AffineFunction
Fixes #275
> 275 bug in affine function

- joss/paper.md
Addressing final JOSS questions.
> 289 joss add the city to all affiliations

- bindings/python/CMakeLists.txt
- bindings/python/include/CommonPybindUtilities.h
- bindings/python/src/IdentityMap.cpp
- bindings/python/src/Wrapper.cpp
- bindings/python/tests/test_IdentityMap.py
Added bindings for IdentityMap in python bindings
> 294 no identity map in python bindings

- bindings/julia/src/ConditionalMapBase.cpp
- bindings/matlab/mat/ConditionalMap.m
- bindings/matlab/src/ConditionalMap_mex.cpp
- bindings/python/src/ConditionalMapBase.cpp
- docs/source/installation.rst
> Add LogDeterminantInputGrad function to bindings.

- MParT/Utilities/LinearAlgebra.h
- src/Utilities/LinearAlgebra.cpp
- tests/Test_LinearAlgebra.cpp
Since #272 is somewhat stalled, I'm pulling the Cholesky factorization out and making it its own PR.
> Add Cholesky Factorization, LU tests

- .docker/environment.yml
- .github/environment.yml
- CMakeLists.txt
- bindings/julia/CMakeLists.txt
- bindings/matlab/CMakeLists.txt
- bindings/python/CMakeLists.txt
I forgot to put cereal as a dependency for the docker conda :/
> Add NLopt dependency, fix docker

- src/MultiIndices/MultiIndexSet.cpp
- tests/MultiIndices/Test_MultiIndexSet.cpp
> Fixed MultiIndexSet::Expand() bug

- CMakeLists.txt
- bindings/python/CMakeLists.txt
- pyproject.toml
- setup.py
@michael-c-brennan This should fix your issue, but could you checkout this branch and test a "local" pip build?   Just cd into the root MParT folder and type `pip install .`
> Fixes in pip install path

- MParT/Utilities/KokkosHelpers.h
- MParT/Utilities/LinearAlgebra.h
Same functionality as before, but addresses issue seen in #375
Might be a problem with NVCC, Kokkos, or their integration? While syntactically this is equivalent to using `std::enable_if`, one of them compiles on the GPU and one doesn't, so I'm going with the one that works.
> Change AddInPlace to lambda

- MParT/MapFactory.h
- MParT/RectifiedMultivariateExpansion.h
- MParT/Sigmoid.h
- MParT/UnivariateExpansion.h
- src/InnerMarginalAffineMap.cpp
- src/MapFactory.cpp
- tests/MultiIndices/Test_MultiIndexSet.cpp
- tests/Test_InnerMarginalAffineMap.cpp
- tests/Test_MapFactory.cpp
- tests/Test_MonotoneComponent.cpp
- tests/Test_MultivariateExpansion.cpp
- tests/Test_RectifiedMultivariateExpansion.cpp
- tests/Test_Serialization.cpp
- tests/Test_Sigmoid.cpp
- tests/Test_UnivariateExpansion.cpp
- Merges `main` into `gpu_compile_24`
- Ensures everything compiles
- Fixes issues with Sigmoids
- Adds tests for sigmoids on GPU
> Finish gpu compile
